---
name: Pull Request checks

"on":
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions: {}

jobs:
  shell_check:
    name: "Shell: Syntax checks"
    uses: scaleway-terraform-modules/workflows/.github/workflows/shell_check.yaml@10afd779716c04fbefb43c1146f6c3d910412edf  # v2.1.12
  tf_module_check:
    name: "Terraform Module: Code checks"
    uses: scaleway-terraform-modules/workflows/.github/workflows/tf_module_check.yaml@10afd779716c04fbefb43c1146f6c3d910412edf  # v2.1.12
  yaml_check:
    name: "YAML: Syntax checks"
    uses: scaleway-terraform-modules/workflows/.github/workflows/yaml_check.yaml@10afd779716c04fbefb43c1146f6c3d910412edf  # v2.1.12
